//
//  DistrictData.swift
//  StopPark
//
//  Created by Arman Turalin on 1/4/20.
//  Copyright © 2020 tech.telegin. All rights reserved.
//

import Foundation

enum DistrictData: String, CaseIterable {
    case adygeya = "01 Республика Адыгея"
    case bashkorstan = "02 Республика Башкортостан"
    case buryatiya = "03 Республика Бурятия"
    case altay = "04 Республика Алтай"
    case dagestan = "05 Республика Дагестан"
    case ingushetiya = "06 Республика Ингушетия"
    case kabardin = "07 Кабардино-Балкарская Республика"
    case kalmykiya = "08 Республика Калмыкия"
    case karachaevo = "09 Республика Карачаево-Черкессия"
    case kareliya = "10 Республика Карелия"
    case komi = "11 Республика Коми"
    case mariy = "12 Республика Марий Эл"
    case mordoviya = "13 Республика Мордовия"
    case saha = "14 Республика Саха (Якутия)"
    case osetiya = "15 Республика Северная Осетия-Алания"
    case tatarstan = "16 Республика Татарстан"
    case tyva = "17 Республика Тыва"
    case udmurtiya = "18 Удмуртская Республика"
    case hakasiya = "19 Республика Хакасия"
    case chuvashiya = "21 Чувашская Республика"
    case altayKray = "22 Алтайский край"
    case krasnodar = "23 Краснодарский край"
    case krasnoyarsk = "24 Красноярский край"
    case primorsk = "25 Приморский край"
    case stavropol = "26 Ставропольский край"
    case khabarovsk = "27 Хабаровский край"
    case amur = "28 Амурская область"
    case arhangel = "29 Архангельская область"
    case astrakhan = "30 Астраханская область"
    case balgorod = "31 Белгородская область"
    case bryansk = "32 Брянская область"
    case vladimir = "33 Владимирская область"
    case volgograd = "34 Волгоградская область"
    case vologodskaya = "35 Вологодская область"
    case voronezh = "36 Воронежская область"
    case ivanov = "37 Ивановская область"
    case irkutsk = "38 Иркутская область"
    case kalinin = "39 Калининградская область"
    case kaluzh = "40 Калужская область"
    case kamchat = "41 Камчатский край"
    case kemer = "42 Кемеровская область - Кузбасс"
    case kirov = "43 Кировская область"
    case kostroma = "44 Костромская область"
    case kurgan = "45 Курганская область"
    case kursk = "46 Курская область"
    case leningrad = "47 Ленинградская область"
    case lipeck = "48 Липецкая область"
    case magadan = "49 Магаданская область"
    case moskvaObl = "50 Московская область"
    case murmansk = "51 Мурманская область"
    case nizhegorod = "52 Нижегородская область"
    case novgorod = "53 Новгородская область"
    case novosib = "54 Новосибирская область"
    case omsk = "55 Омская область"
    case orenburg = "56 Оренбургская область"
    case orlov = "57 Орловская область"
    case penza = "58 Пензенская область"
    case perm = "59 Пермский край"
    case pskov = "60 Псковская область"
    case rostov = "61 Ростовская область"
    case ryazan = "62 Рязанская область"
    case samar = "63 Самарская область"
    case saratov = "64 Саратовская область"
    case sahalin = "65 Сахалинская область"
    case sverdlov = "66 Свердловская область"
    case smolensk = "67 Смоленская область"
    case tombov = "68 Тамбовская область"
    case tver = "69 Тверская область"
    case tomsk = "70 Томская область"
    case tulsk = "71 Тульская область"
    case tumen = "72 Тюменская область"
    case ulyan = "73 Ульяновская область"
    case chelyab = "74 Челябинская область"
    case zabaykal = "75 Забайкальский край"
    case yaroslav = "76 Ярославская область"
    case moscovCity = "77 г. Москва"
    case peter = "78 г. Санкт-Петербург"
    case eurey = "79 Еврейская автономная область"
    case krym = "82 Республика Крым"
    case neneck = "83 Ненецкий автономный округ"
    case hynty = "86 Ханты-Мансийский автономный округ - Югра"
    case chukot = "87 Чукотский автономный округ"
    case yamal = "89 Ямало-Ненецкий автономный округ"
    case sevastopol = "92 г. Севастополь"
    case chechen = "95 Чеченская Республика"
    
    func getCode() -> Int? {
        return Int(String(rawValue.dropLast(2)))
    }
}
